# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.Store'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customertopup',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_top_ups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customertopup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_ups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countertopup',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_top_ups', to=settings.AUTH_USER_MODEL),
        ),
    ]
