# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paid',
        ),
    ]
