# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20160324_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.Store'),
        ),
    ]
