# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20160324_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countertopup',
            options={'permissions': (('view_counter_top_up', 'View counter top up'),), 'verbose_name': 'Top up counter', 'verbose_name_plural': 'Top up counter'},
        ),
        migrations.AlterModelOptions(
            name='customertopup',
            options={'permissions': (('view_customer_top_up', 'View customer top up'),), 'verbose_name': 'Top up pengguna', 'verbose_name_plural': 'Top up pengguna'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('view_transaction', 'View transaction'),), 'verbose_name': 'Transaksi toko', 'verbose_name_plural': 'Transaksi toko'},
        ),
    ]
