# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Toko', 'verbose_name_plural': 'Toko'},
        ),
    ]
