# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160323_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'permissions': (('view_store', 'View store'),), 'verbose_name': 'Toko', 'verbose_name_plural': 'Toko'},
        ),
    ]
