# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160323_2107'),
        ('users', '0004_auto_20160323_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ManyToManyField(to='store.Store'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('counter', 'Counter'), ('customer', 'Customer'), ('staff', 'Staff'), ('store', 'Store')], default='customer', max_length=20),
        ),
    ]
