# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160323_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
