# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160323_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='primary_id_bca',
        ),
    ]
