# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_primary_id_bca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='store',
            new_name='stores',
        ),
    ]
