# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160323_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('counter', 'Counter'), ('customer', 'Customer'), ('staff', 'Staff'), ('store', 'Store')], max_length=20, null=True),
        ),
    ]
