# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160324_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='083896219568', max_length=30),
            preserve_default=False,
        ),
    ]
