# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160325_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stores',
            field=models.ManyToManyField(blank=True, to='store.Store'),
        ),
    ]
